### ISSUE TITLE
Hard split of the different OID4VC crates

### ISSUE THREAD

**Issue by nanderstabel** [impierce/siopv2#42]
### Description

Specifically the SIOPv2, OID4VC and OID4VCI crates need to be properly split. All common/shared code should be migrated to a new crate: `oid4vc-core` or `oid4vc-common`.

Whenever SIOPv2 or OID4VC should be used in unison, their respective feature flags should be used. 

### Motivation

This is necessary in order for SIOPv2 to be used with and without OID4VP and vice versa. 

### To-do List

- [x] Create a new crate and migrate all shared code there.
- [x] #60 
- [ ] Implement feature flags so that SIOPv2 and OID4VP can be used in unison
- [x] Add an integration test to test the implicit flow for siopv2+oid4vp
