### ISSUE TITLE
Add Implicit Flow support

### ISSUE THREAD

**Issue by nanderstabel** [impierce/siopv2#5]
### Description

We need support for the Implicit Flow for SIOPv2 as described in [SIOPv2](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html) as well as in [section 7 of the OIDC-core standard](https://openid.net/specs/openid-connect-core-1_0.html#SelfIssued). The Implicit Flow is summarized as follows:
1. The Relying Party creates a SIOP Request specified [here](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html#name-self-issued-openid-provider-a).
2. The Provider receives a SIOP Request.
3. The Provider [validates the request](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html#name-self-issued-openid-provider-a).
4. The Provider creates a SIOP Response by creating and signing an id_token [following this specification](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html#name-self-issued-openid-provider-au) and also [this specification for ID Tokens](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html#name-self-issued-id-token).
5. The Provider sends the SIOP Request to the Relying Party's `redirect_uri` by a direct HTTP POST request.
6. The Relying Party receives the SIOP Response and validates it following [this](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html#name-self-issued-id-token-valida) specification.

### Motivation

The Implicit Flow is a widely used flow in OpenID Connect, and its support is necessary for our SIOP implementation to be fully compliant with the specification. By implementing the Implicit Flow, we can ensure that our SIOP Provider is able to generate and sign ID Tokens that can be securely transmitted to Relying Parties. This will also expand the interoperability of our SIOP Provider with other OpenID Connect compliant systems.

### Resources

[OIDC-core](https://openid.net/specs/openid-connect-core-1_0.html#SelfIssued)
[SIOPv2](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html)

### To-do List

- [x] Add a `Provider` struct that can validate SIOP Requests and create and sign SIOP Responses (including ID Token).
- [x] Add a `RelyingParty` struct that can create and present a SIOP Request as well as validate SIOP Responses.
- [x] Add support for the IOTA DID method.
