### ISSUE TITLE
Add support for configurable signature types

### ISSUE THREAD

**Issue by nanderstabel** [impierce/siopv2#71]
### Description

Currently the openid4vc libraries only support `EdDSA` as the signature type. There needs to be a way to make the signature types configurable.

### Motivation

Allowing for signature types other than `EdDSA` will make the libraries more versatile. 

### Resources

n/a

### To-do List

- [ ] add support in `proof.rs`
- [ ] add support in `siopv2.rs`
- [ ] add support in `oid4vp.rs`
- [ ] add support in `relying_party.rs`
